### ISSUE TITLE
Create a concept of "image source" for layers

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#10]
Current design of XRWebGLLayer allows only to use an opaque framebuffer. This approach won't work well with the layering system, or even with multiview (where texture array is required). Need to create a a concept of the "image source", the abstract base and then introduce specific implementations of it, for example ImageSourceFramebuffer, ImageSourceTextureArray, ImageSourceTexture, etc. The similar concept exists in OpenXR.

**Comment by toji** [comment]
Not sure if this fits better here or under #11, so I'm just gonna choose this issue.

I've had a few people ask about layering-related features recently and had some time yesterday to give it some thought. In broad strokes I like the breakdown of layer types and layer sources suggested in the [layers core doc](https://github.com/immersive-web/layers/blob/master/layers-core.md), but I'm a bit apprehensive about leaning into the OpenXR style of making the user responsible for allocating and managing the appropriate resources.

The current `XRWebGLLayer` had a nice property in that it would automatically allocate and report the right buffer and viewports for the session. I would like to preserve that perscriptive rendering style for WebXR, as it feels like one of the primary things that allows developers to better cope with the wide array of devices the API may interact with. It feels like the focus should be on describing the desired display properties of the output and letting the API figure out how best to deliver that. Additionally, given the existing media processing capabilities of the web it seems like we have an opportunity to make certain common operations significantly easier.

With that in mind I took a stab at tweaking the current proposal to try and produce something that would mesh with the current render loop flow a bit better. There's some edge cases that this wouldn't support that OpenXR and friends might, but I'm not sure if they're actually useful or not.

Best way to communicate what I'm thinking is via some code snippits, so lets jump into that:

Notes: I'm using `XRLayerSource` rather than the layer core doc's `XRLayerImageSource`, because otherwise you end up with interfaces like `XRImageLayerImageSource`. 🤢 Also looking at quad/equirect layers because I think they help explain the direction I"m thinking of.

IMG tag in quad
```js
  let source = new XRImageLayerSource(xrSession, imgElement);
  let layer = new XRQuadLayer(source, refSpace);
  // These would need to sync up to the frame boundary somehow.
  layer.transform = new XRRigidTransform(/* ... */);
  layer.width = 0.4;
  layer.height = 0.3;
```

Stereo IMG tag in quad
```js
  let source = new XRImageLayerSource(xrSession, imgElement, {
    leftBounds: /* Some rect */ /* probably in UVs? */,
    rightBounds: /* Some rect */
  });
  let layer = new XRQuadLayer(source, refSpace);
  // ...
```

Stereo Video in quad
```js
  let source = new XRVideoLayerSource(xrSession, videoElement, {
    leftBounds: /* Some rect */,
    rightBounds: /* Some rect */
  });
  let layer = new XRQuadLayer(source, refSpace);
  // ...
```

IMG in equirect
```js
  let source = new XRImageLayerSource(xrSession, imgElement);
  let layer = new XREquirectLayer(source, refSpace);
  layer.radius = /* ... */;
  layer.scale = /* ... */;
  layer.bias = /* ... */;
```

These are all fundamentally the same thing. There's very little configuration needed, just point at a media element and tell us which subsection should be shown to which eye, if needed. Should be able to auto-update when needed, so video playback control would happen entirely though the video element.

WebGL Projection Layer
```js
  // Combined this is the equivalent of an XRWebGLLayer
  let source = new XRWebGLLayerSource(xrSession, gl, { /* The usual */ });
  let layer = new XRProjectionLayer(source); /* Can this skip refSpace? */
  
  // Render Loop (same as it ever was)
  gl.bindFramebuffer(gl.FRAMEBUFFER, source.framebuffer);
  for (let view in xrViewerPose.views) {
    let viewport = source.getViewport(view);
    gl.viewport(viewport.x, viewport.y, viewport.width, viewport.height);
    // render
  }
```

WebGL in quad
```js
  let source = new XRWebGLLayerSource(xrSession, gl, { format: "mono", width: 1280, height: 1024 });
  let layer = new XRQuadLayer(source, refSpace);
  // ...

  // Render Loop
  gl.bindFramebuffer(gl.FRAMEBUFFER, source.framebuffer);
  let viewport = source.getEyeViewport("none"); // Not sure about this bit.
  gl.viewport(viewport.x, viewport.y, viewport.width, viewport.height);
  // render
```

Stereo WebGL in quad
```js
  let source = new XRWebGLLayerSource(xrSession, gl, { format: "stereo", width: 1280, height: 1024 });
  let layer = new XRQuadLayer(source, refSpace);
  // ...

  // Render Loop
  gl.bindFramebuffer(gl.FRAMEBUFFER, source.framebuffer);
  for (let eye in ["left", "right"]) {
    let viewport = source.getEyeViewport(eye);
    gl.viewport(viewport.x, viewport.y, viewport.width, viewport.height);
    // render
  }
```

Default `format` for WebGL source is `"projection"`. `"mono"` and `"stereo"`
sources allocate one or two images/viewports respectively, `"projection"`
allocates one per-view. `"mono"` and `"stereo"` sources can't be used with
projection layers. IMG/Video sources are implicitly treated as `"stereo"` sources
but may have overlapping rects per eye, making them effectively mono. As a result
you can't have IMG/Video projection layers.

Shouldn't be any issues with sharing a single source between multiple layers.
Open question whether or not projection could be allowed as a quad/equirect/etc
source. Would need to map from views to eyes somehow.

Alternatively you could leave the stereo and mono options off of the
`XRWebGLLayerSource` and either have an `XRCanvasLayerSource` that works like
the Image and Video sources (maybe even combine them into on big source type?)
or a secondary type of explicitly non-projection WebGL source.

And finally, when we get to texture arrays and WebGPU and such, it would follow a similar pattern:

WebGL Texture Array Projection Layer
```js
  let source = new XRWebGLArrayLayerSource(xrSession, gl, { /* The usual */ });
  let layer = new XRProjectionLayer(source);
  let framebuffer = gl.createFramebuffer();

  // Render Loop
  gl.bindFramebuffer(gl.FRAMEBUFFER, framebuffer);
  for (let view in xrViewerPose.views) {
    let subImage = source.getViewSubImage(view);
    gl.framebufferTextureLayer(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, 
        source.colorTextureArray, 0, subImage.imageIndex);
    gl.framebufferTextureLayer(gl.FRAMEBUFFER, gl.DEPTH_ATTACHMENT, 
        source.depthStencilTextureArray, 0, subImage.imageIndex);
    let viewport = subImage.viewport;
    gl.viewport(viewport.x, viewport.y, viewport.width, viewport.height);
    // render
  }
```

Ignoring the interface/attribute names, which I legitimately don't care much about right now, there's a lot of similarities here to the layers core doc. The primary differences are:
  -  We don't set things like which eye a (non-projection) layer is visible to any more.  Every layer is implicitly shown to both eyes, and the content may be stereo or mono.
  - Allows for layers that don't have to pass through WebGL/WebGPU first, allowing the UA to do whatever optimizations it wants for things like video (and also allowing for no-fuss support of encrypted media.)
  - For WebGL/WebGPU layers we would continue to allow the UA to manage the buffer allocation. Otherwise it's a potential point of developer failure because they MUST allocate the right number of images for each view anyway.

**Comment by cabanier** [comment]
Closing since this work was integrated in the current proposal
