### ISSUE TITLE
Should quad, cylinder and equirect layer support be mandatory for UAs?

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/layers#127]
Currently, step 1 of the algorithm for `createQuadLayer`, `createCylinderLayer` and `createEquirectLayer` says the following:

> 1. If the device does not support the creation of an `XR...Layer`, throw an `NotSupportedError` and abort these steps.

It seems unfortunate if the only way that an app can determine if it's possible to create a layer is to try and fail.  However, even if we solved that, it is a heavy burden to place on web apps tested on one device to the deal with the case where quad, cylinder or equirect layers turn out to be unsupported on the user's device.  For WebGL layers, I could imagine a polyfill that tries to manually render layers 1-n into projection layer 0 using WebGL.  However, for video layers, it would be quite a heavy lift for a polyfill without "DOM to texture" capabilities to simulate the full state machine of an `HTMLVideoElement`, including video scrubbing and decoding.  In the case of encrypted video, a polyfill may be impossible.

While a polyfill for quad, cylinder and equirect layers would often be difficult/impossible for JS code inside the sandbox to implement, it should be straightforward for a UA sitting on an underlying XR platform that does not offer layer support to just stamp those layers onto the final texture before submitting a single projection layer to the XR platform.  While this may not offer the improvement in stability or clarity that the page was seeking with their use of layers, it will allow the page to at least display all of its elements to the user as intended, especially for pages that use video layers.

My suggestion here is to change the language of the layers spec to require that UAs support quad, cylinder and equirect layers, in addition to the projection layers they must support already:
* Remove step 1 from the algorithm for `createQuadLayer`, `createCylinderLayer` and `createEquirectLayer`, bringing those algorithms in line with the current algorithm for `createProjectionLayer`.
* Add explicit spec text that UAs must simulate projection layers, quad layers, cylinder layers and equirect layers, up to some minimum count, even if they are not supported by the underlying XR platform.  Note that this text is already missing for projection layers beyond layer 0, as some underlying XR platforms that do support quad layers may not support more than one projection layer.  We can decide on the minimum required count of supported layers here - [16 is what OpenXR requires](https://github.com/KhronosGroup/OpenXR-SDK/blob/master/include/openxr/openxr.h#L135).

**Comment by cabanier** [comment]
> It seems unfortunate if the only way that an app can determine if it's possible to create a layer is to try and fail. 

Yes, this is indeed unfortunate. I did this intentionally because advertising your supported features has fingerprinting concerns.

> However, even if we solved that, it is a heavy burden to place on web apps tested on one device to the deal with the case where quad, cylinder or equirect layers turn out to be unsupported on the user's device. For WebGL layers, I could imagine a polyfill that tries to manually render layers 1-n into projection layer 0 using WebGL. 

Yes, our plan was to create a polyfill for implementations that don't have layer support.

> However, for video layers, it would be quite a heavy lift for a polyfill without "DOM to texture" capabilities to simulate the full state machine of an `HTMLVideoElement`, including video scrubbing and decoding. 

We already have many real world WebXR sites that use HTMLVideoElements as datasources. Those can easily be adapted to run on layers.

> In the case of encrypted video, a polyfill may be impossible.

Yes, it won't be possible but encrypted video is already a fractured platform.

> My suggestion here is to change the language of the layers spec to require that UAs support quad, cylinder and equirect layers

I'm a bit hesitant to force UAs to take on substantial work, especially if it can be emulated in javascript. It's reasonable to just support a projection layer so you get texture array support which is more efficient.
Of course, if every platform has support for layers, we can make it mandatory.

> * Add explicit spec text that UAs must simulate projection layers, quad layers, cylinder layers and equirect layers, up to some minimum count, even if they are not supported by the underlying XR platform.  Note that this text is already missing for projection layers beyond layer 0, as some underlying XR platforms that do support quad layers may not support more than one projection layer.  We can decide on the minimum required count of supported layers here - [16 is what OpenXR requires](https://github.com/KhronosGroup/OpenXR-SDK/blob/master/include/openxr/openxr.h#L135).

Yes, let me open another issue on this.

**Comment by cabanier** [comment]
/agenda should it be mandatory that UAs support all layers?

**Comment by toji** [comment]
I agree that having spotty layer support is a burden for developers, but I'm also very concerned about the percieved implementation burden for UAs to implement the full layers feature. We've already got [Mozilla suggesting alternate paths](https://github.com/immersive-web/webxr/pull/1019) for getting to, effectively, the XRProjectionLayer feature because "doing the full layers implementation would take considerably more time, compared to extending the existing API."

Perhaps a good compromise would be a two-tier system driven by feature descriptors. Basically if you support the layers at all you MUST support a baseLayer-only projection layer. No feature descriptor needed, perhaps, since it's easy enough to feature detect without it. This has the effect of giving UAs the ability to expose just texture array support if that's all they want. Then, for any more advanced layer usage you have to request the `"layers"` feature discriptor (or maybe `"multi-layer"` is more accurate?). If this succeeds then you are guaranteed access to all the compositor layer types AND support for at least N layers. Significantly higher implementation burden, sure, but more predictable for developers.

Looking forward to discussing this on the next call!

**Comment by cabanier** [comment]
In this week's call we agreed that projection layers will always be supported, even if the layers feature wasn't requested.
Authors can easily feature detect projection layer by checking if `XRWebGLBinding` exists.
