### ISSUE TITLE
Limit scaleFactor

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#162]
As @toji mentioned in https://github.com/immersive-web/layers/pull/160#discussion_r438453506, should we clamp the scaleFactor?

Maybe we should throw an exception if the texture width/height is exceeded with a message that scalefactor should be lowered.

**Comment by toji** [comment]
I don't know that we want to throw an exception. If we did, we'd want to advertise what the acceptable range was so that devs could avoid exceeding it. It seems like allowing the UA to silently adjust the `scaleFactor` as needed would be sufficent. The scaleFactor can be considered a quality/performance hint rather than a hard requirement.

FWIW the corresponding text in the WebXR explainer says:

> The UA may clamp the scale factor however it sees fit, or may round it to a desired increment if needed (for example, fitting the buffer dimensions to powers of two if that is known to increase performance.)

The type of rounding described there certainly doesn't seem like something we should throw exceptions over. It's also worth noting that at least one platform that I know of (Windows Mixed Reality, IIRC) doesn't allow for custom framebuffer sizes at all.

**Comment by cabanier** [comment]
Maybe we should calculate the maximum scalefactor for the views (= the scalefactor that can be applied to the view with the maximum width or height) and apply that to all views.
Otherwise, some views would be higher resolution than others.
