### ISSUE TITLE
What does it mean for two stereo subimages to be "different"?

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/layers#204]
The spec currently says this:

> A stereo layer MUST supply a different `XRSubImage` to render to for each view.

Two questions about this requirement:
* What does the spec mean by "different" here?  Do two different `XRSubImage` instances that refer to the same region count?  Can the regions be slightly different but still overlap?  Or must the regions be non-overlapping?
* If the intention is for the subimages to be non-overlapping, is this requirement actually necessary for some platforms?  For example, for a background layer in a flight simulator, the game could decide to optimize that layer by rendering it mono when all the geometry is far enough away.  Is it necessary to disallow that?

**Comment by cabanier** [comment]
That section is a confusing and should be cut/rephrased. There is normative text later that exactly defines what should happen.
I will create a PR.

**Comment by cabanier** [comment]
> * What does the spec mean by "different" here?  Do two different `XRSubImage` instances that refer to the same region count?  Can the regions be slightly different but still overlap?  Or must the regions be non-overlapping?

Further down the spec defines how these images are created,
The algorithm creates new subimages for each view (and they contain non-overlapping viewports). The current spec text is correct but I removed the "different" keyword since it is a bit confusing.

> * If the intention is for the subimages to be non-overlapping, is this requirement actually necessary for some platforms?  For example, for a background layer in a flight simulator, the game could decide to optimize that layer by rendering it mono when all the geometry is far enough away.  Is it necessary to disallow that?

The game could decide to create a new layer which is mono and swap it out the stereo layer. This is possible without redraw glitches.
There is currently no way to change a layer from stereo to mono.

**Comment by cabanier** [comment]
Addressed with pr #205. Please reopen if you still think there's an issue.
