### ISSUE TITLE
Remove ignoreDepthValues

### ISSUE THREAD

**Issue by toji** [immersive-web/layers#214]
I believe that in a previous conversation we decided that `ignoreDepthValues` wasn't needed any longer because of the fact that depth textures are supplied separately. If the developer doesn't want their depth values used by the compositor, they should allocate their own depth texture and bind it to a framebuffer with the layer-supplied color texture.

Functionally this means you could also get rid of the `XRProjectionLayer` type, since this is the only value on it. That, however, would prevent  `getViewSubImage` from limiting its inputs to only projection layers, so the type may need to stick around as an empty extension of `XRCompositionLayer` anyway.

**Comment by cabanier** [comment]
I don't remember having that conversation.
`ignoreDepthValues` is there to signal to the author that the compositor won't use the depth values to do reprojection.

>If the developer doesn't want their depth values used by the compositor, they should allocate their own depth texture and bind it to a framebuffer with the layer-supplied color texture.

Yes, in that case, they would pass `false` to the [depth parameter](https://immersive-web.github.io/layers/#dom-xrprojectionlayerinit-depth). Passing `true` implies that the author wants to create valid depth data to help out the compositor.

Maybe you are right that we can remove that parameter because what is an author supposed to do with that information?

**Comment by cabanier** [comment]
@toji should we remove the parameter?
If not, I think we should move it to `XRWebGLBinding` because it will then indicate to the author that they should ask for a depth buffer and render the depth to it.

**Comment by cabanier** [comment]
We discussed this in a weekly call and decided to keep the current behavior
