### ISSUE TITLE
Allow higher quality filtering

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#275]
We've seen that a very common use case for layers is the display of documents or UI with text.
Currently, layers are tuned for performance but they have the ability to turn on extra filtering which improves text readability. See https://www.facebook.com/RealityLabs/videos/1021802275341764/ around the 14 minute mark.

Should we make this available for WebXR Layers? I envision that this could be an optional feature that UAs can ignore.

/agenda should we allow higher quality filtering?

**Comment by toji** [comment]
I want to look into the mechanics of how this is set with OpenXR a bit more, but at a high level I don't object to this. Seems like a sensible knob for developers to make performance/readability tradeoffs for a challenging case (text).

I'll also mention that I'm a little reluctant to pile _too_ many knobs onto layers, especially in an environment where we don't have a practical way of validating that they'll be supported by more than one vendor. It's hard in this case, though, because we're handing off so much control of how it's rendering to the compositor, so maybe it's inevitable that our list of settings will grow.

**Comment by cabanier** [comment]
> I want to look into the mechanics of how this is set with OpenXR a bit more, but at a high level I don't object to this. Seems like a sensible knob for developers to make performance/readability tradeoffs for a challenging case (text).

It's going to be part of the structure that lets you control the [sampler state](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSwapchainStateSamplerOpenGLESFB) of the swapchain. I'm unsure if we need the same level of control in WebXR; maybe it's enough to specify `linear` or `bicubic` at layer creation time.

**Comment by cabanier** [comment]
This could also tie into specifying the color profile of the swapchain. (I know @Artyom17 filed an issue on that but I can't find it)

**Comment by cabanier** [comment]
Actually, it might make more sense to set it at runtime. Maybe it could be a parameter on `XRCompositionLayer`.

**Comment by cabanier** [comment]
[Meta added support](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XR_FB_composition_layer_settings) to enhance the quality of composition layers (this includes projection).
I don't remember where we left this but when I turned this on as an experiment, video layers were visibly improved

/agenda add support to layers for different quality settings

**Comment by AdaRoseCannon** [comment]
Removing label, because it was discussed at the last meeting, if this is in error or more discussion is needed please reuse '/agenda'
