### ISSUE TITLE
Must all layers use the same WebGL context?

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/layers#31]
Seems like currently it is possible to use different WebGL contexts for different layers within the same session. This may significantly complicate implementation. Shouldn't we limit all layers to use the same WebGL context explicitly?

**Comment by Manishearth** [comment]
cc @asajeffrey

**Comment by Artyom17** [comment]
>> This may significantly complicate implementation.

Or, maybe not... Will see, trying to implement it now, I'll update the issue if I get significant difficulty.

**Comment by cabanier** [comment]
During the initial discussion, we said that there's no reason to allow multiple contexts.
A potential exception would be if we allow layer creation in web workers but that's further down the line.

**Comment by toji** [comment]
My impression is that it shouldn't be a significant complication (there's nothing about Chrome that would make it so that I'm aware of, may be in other browser but I'd be somewhat surprised.) It would have some useful benefits in terms of tooling, where some libraries could utilize their own context to alleviate worries about interfering with the "main" context's state. (Think of, for example, a FPS counter that just wanted to stick a graph overlay in your scene using a Quad layer)

**Comment by cabanier** [comment]
Maybe we should leave the spec in its current shape unless an implementor raises an objection.
I will close this issue if nobody objects.
