### ISSUE TITLE
Should the requestxxx APIs use promises?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#32]
Currently the APIs to create layers all return a promise.
This means that the promise for the layers is fulfilled outside a Raf. I think this is confusing because the author won't be allowed to use the layers there.
Moreover, XRWebGLLayer can just be constructed so why can't we have immediate layer creation?

I think we should get rid of the promises and return the layer object directly.

**Comment by toji** [comment]
I don't object to allowing direct return of a (nullable) object if we know with reasonable certainty that UAs won't need to do a round trip check to the runtime to verify whether or not the layer can be created as requested. I think that should be feasible, but we'll want to check.

In terms of using a layer inside a rAF call, I don't think that would work even if the object returned immediately? The layers are set via updateRenderState, which intentionally defers applying changes made in the rAF call until the next rAF. This is so that the compositor can be confident about the state being used for the frame in the case that the runtime needs to do some prep for it. In this specific case, I can imagine that it would be useful to know which layers are going to be used during the frame so that you only have to get swapchain images for the ones that are actually being drawn. If the active layers can change during the rAF callback then the UA can't do any work to prepare the layer's to be composited in advance or, conversely, has to do work for every layer, whether it's in use or not, on the off chance that it _might_ be used.

**Comment by cabanier** [comment]
/agenda let's discuss if we need the promises

**Comment by Manishearth** [comment]
>  I think this is confusing because the author won't be allowed to use the layers there.

You need to `updateRenderState()` first so it's better if these are exposed outside of the raf.

**Comment by cabanier** [comment]
During today's meeting, nobody objected to removing the promise and returning the object.
I will the needed changes to the spec.
