### ISSUE TITLE
Should the depth stencil buffer be optional

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#35]
I updated the layers proposal so on platforms that don't use the depth buffer for reprojection, the depth/stencil texture is always null.
Was that the right thing to do?
/agenda

**Comment by toji** [comment]
Hm... so the idea is that even if you ask for a depth buffer but it's not used in compositing it will return null? Not sure I'm on board with that, as it makes for more work for the developer when it doesn't seem like a large burden for the UA? Also may be a pit of failure where the developers hardware makes use of it and so they don't realize that they'll need to allocate their own textures in some cases.

I do wonder if there's a variant of this that would make more sense in this case, though? Since we're no longer doing the opaque framebuffer thing here we could say that if you DO request a depth buffer then you're expected to always ensure the values in it are appropriate for compositing. If you're not willing to do that then you can allocate your own depth buffers instead. Has the benefit of eliminating one of the more confusing options in the current `XRWebGLLayer`.

I will say that I'm a little concerned that devs who choose to allocate their own depth buffers won't have all the information needed to do so (number of views, specifically) until rAF callback has already started, which isn't the optimal point to allocate buffers. Maybe we want an event on the layer to indicate when the attachment shape (width, height, image count) changes?

**Comment by cabanier** [comment]
> Hm... so the idea is that even if you ask for a depth buffer but it's not used in compositing it will return null?

Correct. That is what the spec currently says.

> Not sure I'm on board with that, as it makes for more work for the developer when it doesn't seem like a large burden for the UA? Also may be a pit of failure where the developers hardware makes use of it and so they don't realize that they'll need to allocate their own textures in some cases.

That is true which is why I raised this issue. If the hardware supports it and the author only tested on hardware that doesn't use depth for compositing, it will result in a sub-par experience.
On the other hand, it does allow the author to allocate their own depth buffer instead of relying on the default one that the UA would allocate.

> I do wonder if there's a variant of this that would make more sense in this case, though? Since we're no longer doing the opaque framebuffer thing here we could say that if you DO request a depth buffer then you're expected to always ensure the values in it are appropriate for compositing. If you're not willing to do that then you can allocate your own depth buffers instead. Has the benefit of eliminating one of the more confusing options in the current `XRWebGLLayer`.

Yes. I *think* this is another argument for leaving the spec as is.

> I will say that I'm a little concerned that devs who choose to allocate their own depth buffers won't have all the information needed to do so (number of views, specifically) until rAF callback has already started, which isn't the optimal point to allocate buffers. Maybe we want an event on the layer to indicate when the attachment shape (width, height, image count) changes?

Wouldn't it only be slow for 1 frame? It could also be the first frame. 
Maybe it's not worth adding a callback...

**Comment by toji** [comment]
> Yes. I _think_ this is another argument for leaving the spec as is.

I should probably clarify. I'm suggesting that if a developer asks for a depth texture we always give it to them, unconditionally, but we say that anything they put in the depth buffer is fair game for compositing. If they want to avoid that then they should allocate their own.

My primary concern is simply that we don't put users in a position where their content unexpectedly breaks on some devices.

> Wouldn't it only be slow for 1 frame? It could also be the first frame.
> Maybe it's not worth adding a callback...

Yeah, I'm probably overthinking it. Especially since the vast majority of hardware won't try and change the size or number of textures after the layer has been allocated initially. If we find out later that this is a real problem then it's easy enough to add to the API later on without backwards compatibility breaks.

**Comment by cabanier** [comment]
OK. I will change the spec and our implementation so the depth buffer is always allocated.

**Comment by cabanier** [comment]
While implementing some test code, I realized that I needed to enable the [WEBGL_depth_texture](https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture/) extension in order to create a texture that can be attached as a depth buffer.

Should we require that this extension is enabled by the author?

**Comment by cabanier** [comment]
or we can define the `depthstenciltexture` to be of type `WebGLRenderbuffer`.

**Comment by cabanier** [comment]
or maybe we should require that the context is WebGL2 or that the extension is enabled.

**Comment by Artyom17** [comment]
> While implementing some test code, I realized that I needed to enable the [WEBGL_depth_texture](https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture/) extension in order to create a texture that can be attached as a depth buffer.

I believe in WebGL 2 it is not required (i.e. enabled by default).

**Comment by Artyom17** [comment]
The benefit to have depth buffer controlled by UA is ability to do some optimizations under the hood, such as discarding the content of the buffer at the end of each frame (otherwise, it will be resolved (MSAA), i.e. wasted GPU time)....
I am probably fine with having depth / stencil  texture even though it is not used for compositing. Let me try to implement it and will see how it goes and which culprits I can hit.
