### ISSUE TITLE
Should layer's init structure have all the attributes?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/layers#83]
Currently, only non-changeable parameters are part of the init structure.
@thetuvix and @Manishearth believe that the space and the transform should be part of that init.
@Manishearth argued that all attributes for a layer should also be in that structure.

I think the current API design is more consistent and it's easy for authors to change the attributes after the layer structure.

**Comment by Manishearth** [comment]
This is pretty standard practice in web APIs, if something is an attribute and you have an init dict, you should have optional dict values if at all possible.

**Comment by thetuvix** [comment]
_Pulling in my relevant comment from [the original issue](https://github.com/immersive-web/layers/issues/75#issuecomment-614354603):_

A key gotcha for quad layers is the big difference in reprojection behavior between a head-locked quad and a world-locked quad placed in the same location.

If an app is trying to render a video quad at a fixed place in the world, but `"viewer"` reference space is the default here, the app may just update the quad position every frame with the quad's pose in viewer space. However, if the app does that, the quad will jitter badly, as reprojection will keep it head-locked rather than keeping it stable in the world.

In all other parts of the WebXR API, we have apps explicitly specify the `XRSpace` they intend to reason in. For layers in particular, apps will be better off if we just have them explicitly set the relevant reference space on each of their layers, even if many layers end up in `"viewer"` space. With that, the correct path for developers becomes the easiest: set their quad layer's reference space as their scene's core reference space, and then just set its position once.

**Comment by thetuvix** [comment]
One other case that was mentioned in the original thread was the "lazy headlock" case of an app always positioning some body-locked UI in viewer space and then giving some springiness to it so it didn't appear completely head-locked.  On HoloLens, we call that tag-along UI.

However, that kind of springy tag-along behavior is explicitly dampened to _avoid_ ingesting any sudden head movement in a given frame - that's what makes it feel more comfortable that true head-locking to users.  This means that when the compositor realizes that there was head movement that needs to be fixed in reprojection, it would introduce unnecessary jitter if the developer chose `viewer` space as their underlying space for the quad.  The correct implementation from the developer is to specify `local`, or `unbounded` space there, before they then adjust the position each frame.

**Comment by cabanier** [comment]
> However, that kind of springy tag-along behavior is explicitly dampened to _avoid_ ingesting any sudden head movement in a given frame - that's what makes it feel more comfortable than true head-locking to users. This means that when the compositor realizes that there was head movement that needs to be fixed in reprojection, it would introduce unnecessary jitter if the developer chose `viewer` space as their underlying space for the quad. The correct implementation from the developer is to specify `local`, or `unbounded` space there, before they then adjust the position each frame.

Are you saying that we should add a note to the spec, telling authors about this issue?
Or should change the space to not default to `viewer` space because it's rarely the right thing to use?

**Comment by cabanier** [comment]
Or both :-)

**Comment by thetuvix** [comment]
Perhaps it's worth a non-normative section or explainer pointing out when you'd use different base spaces?

Here are the examples that come to my mind now:
* **`XRProjectionLayer` in `"local"`/`"local-floor"`/`"bounded"`/`"bounded-floor"`/`"unbounded"` space:** Primary world layer or fixed-foveation subregion layer
  * Choosing `"viewer"` to stabilize the primary or secondary projection layer would disable all reprojection
* **`XRQuadLayer` in `"viewer"` space:** Head-locked constant-size reticle in center of screen
* **`XRQuadLayer` or `XRCylinderLayer` in `"local"`/`"unbounded"` space:** Springy body-locked UI
  * Choosing `"viewer"` would disable positional and rotational reprojection of the UI quad in the world, defeating the app's dampened tag-along behavior
* **`XRQuadLayer` or `XRCylinderLayer` in `"local"`/`"local-floor"`/`"bounded"`/`"bounded-floor"`/`anchorSpace`**: World-locked video, placed by the user
  * Choosing `"viewer"` would disable positional and rotational reprojection of the video in the world, defeating the app's dampened tag-along behavior
* **`XREquirectLayer`/`XRCubemapLayer` in `"local"` space**: 360-degree video or skybox
  * Choosing `"viewer"` and fixing orientation each frame would disable rotational reprojection

In general, I don't see too many use cases for head-locked layers.  Even in the "head gaze cursor" scenario, we generally encourage [world-locked cursors](https://docs.microsoft.com/windows/mixed-reality/cursors) that align to the surface of the object they're on and reproject along with that object, so that the cursor feels like a part of the world rather than something on your glasses.

I would not encourage developer use of `"viewer"` space to stabilize any layer types, as this will almost always defeat positional or rotational reprojection and result in a loss in stability of the rendered content relative to the world.  Requiring developers to specify their intended world-locked space could go a long way to discouraging `"viewer"` space here.

This aligns with guidance I see in [Oculus docs](https://developer.oculus.com/documentation/unity/unity-ovroverlay/):

> **World-locked vs Head-locked Layers**
> Overlay layers should almost always be world-locked, which means that they maintain their position with respect to the world behind it.
> 
> * World-locked overlays use TimeWarp, similar to non-overlay content, and are much less prone to judder.
> * Head-locked overlays bypass TimeWarp and exactly follow head motion. The exception being small UI elements like a gaze cursor or targeting reticle.
> 
> Overlays are world-locked by default. To make a head-locked overlay, make the layer (usually a Quad) a child of OVRCameraRig center eye anchor.

It may also be worth renaming `space` to `stabilizationSpace` or `reprojectionSpace` or such, to drive home that this decision will impact the behavior of reprojection.

**Comment by cabanier** [comment]
/agenda should we rename `space` to `stabilizationSpace`?

**Comment by Manishearth** [comment]
Might be worth discussing the main issue about init dicts as well during this (or a separate) agenda topic.

**Comment by cabanier** [comment]
> Might be worth discussing the main issue about init dicts as well during this (or a separate) agenda topic.

Let's see if we can resolve this today and then I will open up another agenda item.

**Comment by Manishearth** [comment]
Sounds good to me!

**Comment by cabanier** [comment]
@thetuvix can you put your comments in a new issue?
I prefer to keep this on just about if parameters should be part of the initial structure.

If you don't have time, would you mind if I do it?

**Comment by cabanier** [comment]
@thetuvix I will open up a new issue to handle the default space.

**Comment by cabanier** [comment]
/agenda Should we have init structures for each layer type so author can pass everything at construction

**Comment by cabanier** [comment]
In this week's call there was general consensus that we should have init structures for each of the layers. I will address this in an upcoming PR.

**Comment by cabanier** [comment]
Fixed with PR #120
